device/esp_tinyusb:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1

host/class:
  enable:
    - if: SOC_USB_OTG_SUPPORTED == 1

host/class/cdc/usb_host_cdc_acm/host_test:
  enable:
    - if: IDF_TARGET in ["linux"] and (IDF_VERSION_MAJOR >= 5 and IDF_VERSION_MINOR >= 4)
